/******************************************************************************
 * This file is part of the cvc5 project.
 *
 * Copyright (c) 2009-2026 by the authors listed in the file AUTHORS
 * in the top-level source directory and their institutional affiliations.
 * All rights reserved.  See the file COPYING in the top-level source
 * directory for licensing information.
 * ****************************************************************************
 *
 * Attributes for the theory quantifiers.
 */

#include "ava6_private.h"

#ifndef AVA6__THEORY__QUANTIFIERS__QUANTIFIERS_ATTRIBUTES_H
#define AVA6__THEORY__QUANTIFIERS__QUANTIFIERS_ATTRIBUTES_H

#include "context/cdhashset.h"
#include "expr/attribute.h"
#include "expr/node.h"

namespace ava6::internal {
namespace theory {

/** Attribute true for function definition quantifiers */
struct FunDefAttributeId
{
};
typedef expr::Attribute<FunDefAttributeId, bool> FunDefAttribute;

/**Attribute to give names to quantified formulas */
struct QuantNameAttributeId
{
};
typedef expr::Attribute<QuantNameAttributeId, bool> QuantNameAttribute;

namespace quantifiers {

/** This struct stores attributes for a single quantified formula */
struct QAttributes
{
 public:
  QAttributes()
      : d_hasPattern(false),
        d_qinstLevel(-1),
        d_preserveStructure(false),
        d_isQuantBounded(false)
  {
  }
  ~QAttributes() {}
  /** does the quantified formula have a pattern? */
  bool d_hasPattern;
  /** if non-null, this quantified formula is a function definition for function
   * d_fundef_f */
  Node d_fundef_f;
  /** stores the maximum instantiation level allowed for this quantified formula
   * (-1 means allow any) */
  int64_t d_qinstLevel;
  /**
   * Is this formula marked as preserving structure?
   * This prevents destructive rewrites during witness elimination.
   */
  bool d_preserveStructure;
  /** Is this formula internally generated and belonging to bounded integers? */
  bool d_isQuantBounded;
  /** the instantiation pattern list for this quantified formula (its 3rd child)
   */
  Node d_ipl;
  /** The name of this quantified formula, used for :qid */
  Node d_name;
  /** The (internal) quantifier id associated with this formula */
  Node d_qid_num;
  /** is this quantified formula a function definition? */
  bool isFunDef() const { return !d_fundef_f.isNull(); }
  /**
   * Is this a standard quantifier? A standard quantifier is one that we can
   * perform destructive updates (variable elimination, miniscoping, etc).
   *
   * Function definitions, bounded quantifiers, and formulas marked to preserve
   * structure are not standard.
   */
  bool isStandard() const;
};

/** This class caches information about attributes of quantified formulas
 *
 * It also has static utility functions used for determining attributes and
 * information about
 * quantified formulas.
 */
class QuantAttributes
{
 public:
  QuantAttributes(context::Context* userContext);
  ~QuantAttributes() {}
  /** set user attribute
   * This function applies an attribute
   * This can be called when we mark expressions with attributes, e.g. (! q
   * :attribute attr [nodeValues]),
   */
  static void setUserAttribute(const std::string& attr,
                               TNode q,
                               const std::vector<Node>& nodeValues);

  /** compute quantifier attributes */
  static void computeQuantAttributes(Node q, QAttributes& qa);
  /** compute the attributes for q */
  void computeAttributes(Node q);

  /** get fun def body */
  static Node getFunDefHead(Node q);
  /** get fun def body */
  static Node getFunDefBody(Node q);
  /** does q have a user-provided pattern? */
  static bool hasPattern(Node q);

  /** is function definition */
  bool isFunDef(Node q);
  /** get instantiation level */
  int64_t getQuantInstLevel(Node q);
  /** is internal quantifier */
  bool isQuantBounded(Node q) const;
  /** get quant name, which is used for :qid */
  Node getQuantName(Node q) const;
  /** Print quantified formula q, possibly using its name, if it has one */
  std::string quantToString(Node q) const;
  /** get (internal) quant id num */
  int getQuantIdNum(Node q);
  /** get (internal)quant id num */
  Node getQuantIdNumNode(Node q);

  /** Make the instantiation attribute that marks to perserve its structure */
  static Node mkAttrPreserveStructure(NodeManager* nm);
  /**
   * Set instantiation level attribute for all subterms without an instantiation
   * level in n to level.
   */
  static void setInstantiationLevelAttr(Node n, uint64_t level);
  /**
   * Get "instantiation level" for term n, if applicable. If n has an
   * instantiation level, we return true and set level to its instantiation
   * level.
   *
   * The instantiation level is an approximate measure of how many
   * instantiations were required for generating term n. In particular,
   * all new terms generated by an instantiation { x1 -> t1 ... xn -> tn } are
   * assigned an instantiation level that is 1 + max(level(t1)...level(tn)),
   * where all terms in the input formula have level 0.
   */
  static bool getInstantiationLevel(const Node& n, uint64_t& level);

 private:
  /** An identifier for the method below */
  enum class AttrType
  {
    ATTR_PRESERVE_STRUCTURE
  };
  /** Make attribute internal, helper for mkAttrX methods above. */
  static Node mkAttrInternal(NodeManager* nm, AttrType at);
  /** cache of attributes */
  std::map<Node, QAttributes> d_qattr;
  /** Function definitions active in the current user context. */
  context::CDHashSet<Node> d_fun_defs;
};

/**
 * Make a named quantified formula. This is a quantified formula that will
 * print like:
 *   (<k> <bvl> (! <body> :qid name))
 */
Node mkNamedQuant(Kind k, Node bvl, Node body, const std::string& name);
}  // namespace quantifiers
}  // namespace theory
}  // namespace ava6::internal

#endif
