id     = "ARRAYS"
name   = "Arrays Theory"

[[option]]
  name       = "arraysEagerIndexSplitting"
  category   = "regular"
  long       = "arrays-eager-index"
  type       = "bool"
  default    = "true"
  help       = "turn on eager index splitting for generated array lemmas"


