id     = "BASE"
name   = "Base"

[[option]]
  name       = "inputLanguage"
  alias      = ["input-language"]
  category   = "common"
  short      = "L"
  long       = "lang=LANG"
  type       = "Language"
  default    = "Language::LANG_AUTO"
  handler    = "stringToLanguage"
  predicates = ["setInputLanguage"]
  includes   = ["options/language.h"]
  help       = "force input language (default is \"auto\"; see --lang help)"

[[option]]
  name       = "verbosity"
  long       = "verbosity=N"
  category   = "common"
  type       = "int64_t"
  default    = "0"
  predicates = ["setVerbosity"]
  help       = "the verbosity level of ava6"

[[option]]
  category   = "common"
  short      = "v"
  long       = "verbose"
  type       = "bool"
  alternate  = false
  predicates = ["increaseVerbosity"]
  help       = "increase verbosity (may be repeated)"

[[option]]
  category   = "common"
  short      = "q"
  long       = "quiet"
  type       = "bool"
  alternate  = false
  predicates = ["decreaseVerbosity"]
  help       = "decrease verbosity (may be repeated)"

[[option]]
  name       = "incrementalSolving"
  category   = "common"
  short      = "i"
  long       = "incremental"
  type       = "bool"
  default    = "true"
  help       = "enable incremental solving"

[[option]]
  name       = "statistics"
  long       = "stats"
  category   = "common"
  type       = "bool"
  default    = "false"
  predicates = ["setStats"]
  help       = "give statistics on exit"

[[option]]
  name       = "statisticsAll"
  long       = "stats-all"
  category   = "common"
  type       = "bool"
  default    = "false"
  predicates = ["setStatsDetail"]
  help       = "print unchanged (defaulted) statistics as well"

[[option]]
  name       = "statisticsInternal"
  long       = "stats-internal"
  category   = "common"
  type       = "bool"
  default    = "false"
  predicates = ["setStatsDetail"]
  help       = "print internal (non-public) statistics as well"

[[option]]
  name       = "statisticsEveryQuery"
  long       = "stats-every-query"
  category   = "regular"
  type       = "bool"
  default    = "false"
  predicates = ["setStatsDetail"]
  help       = "in incremental mode, print stats after every satisfiability or validity query"

[[option]]
  name       = "parseOnly"
  category   = "common"
  long       = "parse-only"
  type       = "bool"
  default    = "false"
  help       = "exit after parsing input"

[[option]]
  name       = "preprocessOnly"
  category   = "common"
  long       = "preprocess-only"
  type       = "bool"
  default    = "false"
  help       = "exit after preprocessing input"

[[option]]
  short      = "o"
  category   = "common"
  long       = "output=TAG"
  type       = "OutputTag"
  default    = "NONE"
  predicates = ["enableOutputTag"]
  help       = "Enable output tag."
  help_mode  = "Output tags."
[[option.mode.NONE]]
  name = "none"
[[option.mode.INST]]
  name = "inst"
  help = "print instantiations during solving"
  description = "With ``-o inst``, ava6 prints information about quantifier instantions for individual quantifers."
  example-file = "regress1/quantifiers/qid-debug-inst.smt2"
[[option.mode.INST_STRATEGY]]
  name = "inst-strategy"
  help = "prints a summary of the instantiation techniques as they are run."
  description = "With ``-o inst-strategy``, ava6 prints a summary of the instantiation techniques as they are run."
  example-file = "regress2/quantifiers/javafe.tc.CheckCompilationUnit.001.smt2"
[[option.mode.TRIGGER]]
  name = "trigger"
  help = "print selected triggers for quantified formulas"
  description = "With ``-o trigger``, ava6 prints the selected triggers when solving a quantified formula."
  example-file = "regress1/quantifiers/qid-debug-inst.smt2"
[[option.mode.RAW_BENCHMARK]]
  name = "raw-benchmark"
  help = "print the benchmark back on the output verbatim as it is processed"
  description = "With ``-o raw-benchmark``, ava6 prints the benchmark back just as it has been parsed."
  example-file = "regress0/datatypes/datatype-dump.cvc.smt2"
[[option.mode.LEARNED_LITS]]
  name = "learned-lits"
  help = "print input literals that hold globally"
  description = "With ``-o learned-lits``, ava6 prints input literals that it has learned to hold globally."
  example-file = "regress0/printer/learned-lit-output.smt2"
[[option.mode.SUBS]]
  name = "subs"
  help = "print top-level substitutions learned during preprocessing"
  description = "With ``-o subs``, ava6 prints top-level substitutions learned during preprocessing."
  example-file = "regress0/printer/print_subs.smt2"
[[option.mode.POST_ASSERTS]]
  name = "post-asserts"
  help = "print a benchmark corresponding to the assertions of the input problem after preprocessing"
  description = "With ``-o post-asserts``, ava6 prints a benchmark corresponding to the assertions of the input problem after preprocessing."
  example-file = "regress0/printer/post-asserts-output.smt2"
[[option.mode.PRE_ASSERTS]]
  name = "pre-asserts"
  help = "print a benchmark corresponding to the assertions of the input problem before preprocessing"
  description = "With ``-o pre-asserts``, ava6 prints a benchmark corresponding to the assertions of the input problem before preprocessing."
  example-file = "regress0/printer/pre-asserts-output.smt2"
[[option.mode.DEEP_RESTART]]
  name = "deep-restart"
  help = "print when ava6 performs a deep restart along with the literals it has learned"
  description = "With ``-o deep-restart``, ava6 prints when it performs a deep restart along with the literals it has learned."
  example-file = "regress0/printer/deep-restart-output.smt2"
[[option.mode.INCOMPLETE]]
  name = "incomplete"
  help = "print reason why ava6 answers unknown for any given check-sat query"
  description = "With ``-o incomplete``, ava6 prints reason for why it answers unknown for any given check-sat query."
  example-file = "regress0/printer/incomplete.smt2"
[[option.mode.LEMMAS]]
  name = "lemmas"
  help = "print lemmas as they are added to the SAT solver"
  description = "With ``-o lemmas``, ava6 prints lemmas as they are added to the SAT solver."
  example-file = "regress0/printer/print_sat_lemmas.smt2"
[[option.mode.TRUSTED_PROOF_STEPS]]
  name = "trusted-proof-steps"
  help = "print formulas corresponding to trusted proof steps in final proofs"
  description = "With ``-o trusted-proof-steps``, ava6 prints formulas corresponding to trusted proof steps in final proofs."
  example-file = "regress0/printer/print_trusted_proof_steps.smt2"
[[option.mode.UNSAT_CORE_BENCHMARK]]
  name = "unsat-core-benchmark"
  help = "print the corresponding benchmark when successfully computing an unsat core."
  description = "With ``-o unsat-core-benchmark``, ava6 prints the corresponding benchmark when it successfully computes an unsat core."
  example-file = "regress0/printer/print_unsat_core.smt2"
[[option.mode.UNSAT_CORE_LEMMAS_BENCHMARK]]
  name = "unsat-core-lemmas-benchmark"
  help = "print the corresponding benchmark when successfully computing an unsat core with theory lemmas."
  description = "With ``-o unsat-core-lemmas-benchmark``, ava6 prints the corresponding benchmark when it successfully computes an unsat core that includes the theory lemmas used."
  example-file = "regress0/printer/print_unsat_core_lemmas.smt2"
[[option.mode.UNSAT_CORE_LEMMAS]]
  name = "unsat-core-lemmas"
  help = "print diagnostic information on lemmas that appear in an unsat core with theory lemmas"
  description = "With ``-o unsat-core-lemmas``, ava6 prints diagnostic information on lemmas that appear in an unsat core with theory lemmas."
  example-file = "regress0/printer/print_unsat_core_lemmas.smt2"
[[option.mode.OPTIONS_AUTO]]
  name = "options-auto"
  help = "prints the options set during automatic configuration."
  description = "With ``-o options-auto``, ava6 prints the options set during automatic configuration."
  example-file = "regress0/printer/print_options_auto.smt2"
[[option.mode.RARE_DB]]
  name = "rare-db"
  help = "upon initialization, print the set of (non-expert) RARE rewrite rules as they are defined in the proof signature."
  description = "With ``-o rare-db``, upon initialization, ava6 prints the entire set of (non-expert) RARE rewrite rules as they are defined in the proof signature."
[[option]]
  name       = "outputTagHolder"
  category   = "undocumented"
  includes   = ["<bitset>"]
  type       = "std::bitset<static_cast<size_t>(OutputTag::__MAX_VALUE)+1>"
  default    = '{}'

[[option]]
  name       = "cumulativeMillisecondLimit"
  category   = "common"
  long       = "tlimit=MS"
  type       = "uint64_t"
  default    = "0"
  help       = "set time limit in milliseconds of wall clock time"

[[option]]
  name       = "perCallMillisecondLimit"
  category   = "common"
  long       = "tlimit-per=MS"
  type       = "uint64_t"
  default    = "0"
  help       = "set time limit per query in milliseconds"

[[option]]
  name       = "cumulativeResourceLimit"
  category   = "common"
  long       = "rlimit=N"
  type       = "uint64_t"
  default    = "0"
  help       = "set resource limit"

[[option]]
  name       = "perCallResourceLimit"
  alias      = ["reproducible-resource-limit"]
  category   = "common"
  long       = "rlimit-per=N"
  type       = "uint64_t"
  default    = "0"
  help       = "set resource limit per query"

# --rweight is used to override the default of one particular resource weight.
# It can be given multiple times to override multiple weights. When options are
# parsed, the resource manager might now be created yet, and it is not clear
# how an option handler would access it in a reasonable way. The option handler
# thus merely puts the data in another option that holds a vector of strings.
# This other option "resourceWeightHolder" has the sole purpose of storing
# this data in a way so that the resource manager can access it in its
# constructor.
[[option]]
  name       = "resourceWeightHolder"
  category   = "undocumented"
  type       = "std::vector<std::string>"
  default    = '{}'


