id     = "PROP"
name   = "SAT Layer"

[[option]]
  name       = "preRegisterMode"
  category   = "regular"
  long       = "preregister-mode=MODE"
  type       = "PreRegisterMode"
  default    = "EAGER"
  help       = "Modes for when to preregister literals."
  help_mode  = "Modes for when to preregister literals."
[[option.mode.EAGER]]
  name = "eager"
  help = "Preregister literals when they are registered as literals in the SAT solver."
[[option.mode.LAZY]]
  name = "lazy"
  help = "Preregister literals when they are asserted by the SAT solver."

