id     = "SMT"
name   = "SMT Layer"

[[option]]
  name       = "simplificationMode"
  alias      = ["simplification-mode"]
  category   = "regular"
  long       = "simplification=MODE"
  type       = "SimplificationMode"
  default    = "BATCH"
  help       = "choose simplification mode, see --simplification=help"
  help_mode  = "Simplification modes."
[[option.mode.NONE]]
  name = "none"
  help = "Do not perform nonclausal simplification."
[[option.mode.BATCH]]
  name = "batch"
  help = "Save up all ASSERTions; run nonclausal simplification and clausal (MiniSat) propagation for all of them only after reaching a querying command (CHECKSAT or QUERY or predicate SUBTYPE declaration)."

[[option]]
  name       = "staticLearning"
  category   = "regular"
  long       = "static-learning"
  type       = "bool"
  default    = "true"
  help       = "use static learning (on by default)"

[[option]]
  name       = "produceModels"
  category   = "common"
  short      = "m"
  long       = "produce-models"
  type       = "bool"
  default    = "false"
  help       = "support the get-value and get-model commands"

[[option]]
  name       = "checkModels"
  category   = "common"
  long       = "check-models"
  type       = "bool"
  default    = "false"
  help       = "after SAT/INVALID/UNKNOWN, check that the generated model satisfies user assertions"

[[option]]
  name       = "debugCheckModels"
  category   = "common"
  long       = "debug-check-models"
  type       = "bool"
  default    = "false"
  help       = "after SAT/INVALID/UNKNOWN, check that the generated model satisfies user and internal assertions"

[[option]]
  name       = "checkModelSubsolver"
  category   = "common"
  long       = "check-model-subsolver"
  type       = "bool"
  default    = "true"
  help       = "use subsolver to compute values when applicable in calls to get-value and check-models"

[[option]]
  name       = "produceProofs"
  category   = "common"
  long       = "produce-proofs"
  type       = "bool"
  default    = "false"
  help       = "produce proofs, support check-proofs and get-proof"

[[option]]
  name       = "checkProofs"
  category   = "common"
  long       = "check-proofs"
  type       = "bool"
  default    = "false"
  help       = "after UNSAT/VALID, check the generated proof (with proof)"

[[option]]
  name       = "produceUnsatCores"
  category   = "common"
  long       = "produce-unsat-cores"
  type       = "bool"
  default    = "false"
  help       = "turn on unsat core generation. Unless otherwise specified, cores will be produced using SAT soving under assumptions and preprocessing proofs."

[[option]]
  name       = "printCoresFull"
  category   = "regular"
  long       = "print-cores-full"
  type       = "bool"
  default    = "false"
  help       = "print all formulas regardless of whether they are named, e.g. in unsat cores"

[[option]]
  name       = "checkUnsatCores"
  category   = "common"
  long       = "check-unsat-cores"
  type       = "bool"
  default    = "false"
  help       = "after UNSAT/VALID, produce and check an unsat core (expensive)"

[[option]]
  name       = "unsatAssumptions"
  category   = "common"
  long       = "produce-unsat-assumptions"
  type       = "bool"
  default    = "false"
  help       = "turn on unsat assumptions generation"

[[option]]
  name       = "produceAssignments"
  category   = "regular"
  long       = "produce-assignments"
  type       = "bool"
  default    = "false"
  help       = "support the get-assignment command"

[[option]]
  name       = "produceAssertions"
  category   = "regular"
  long       = "produce-assertions"
  type       = "bool"
  alias      = ["interactive-mode"]
  default    = "true"
  help       = "keep an assertions list. Note this option is always enabled."

[[option]]
  name       = "solveRealAsInt"
  category   = "regular"
  long       = "solve-real-as-int"
  type       = "bool"
  default    = "false"
  help       = "attempt to solve a pure real satisfiable problem as an integer problem (for non-linear)"

