id     = "THEORY"
name   = "Theory Layer"

[[option]]
  name       = "condenseFunctionValues"
  category   = "common"
  long       = "condense-function-values"
  type       = "bool"
  default    = "true"
  help       = "condense values for functions in models rather than explicitly representing them"

[[option]]
  name       = "defaultFunctionValueMode"
  category   = "common"
  long       = "default-function-value-mode=MODE"
  type       = "DefaultFunctionValueMode"
  default    = "FIRST"
  help       = "mode for choosing default values for functions"
  help_mode  = "Defines mode for choosing default values for functions."
[[option.mode.FIRST]]
  name = "first"
  help = "The default value is equal to the value of the first application found of that function when applicable, or the first enumerated term otherwise."
[[option.mode.FIRST_ENUM]]
  name = "first-enum"
  help = "The default value is equal to the first enumerated value of its range type."
[[option.mode.HOLE]]
  name = "hole"
  help = "The default value is equal to a distinguished variable."

