/******************************************************************************
 * This file is part of the cvc5 project.
 *
 * Copyright (c) 2009-2026 by the authors listed in the file AUTHORS
 * in the top-level source directory and their institutional affiliations.
 * All rights reserved.  See the file COPYING in the top-level source
 * directory for licensing information.
 * ****************************************************************************
 *
 * Implementation of the command pattern on SolverEngines.
 *
 * Command objects are generated by the parser (typically) to implement the
 * commands in parsed input (see Parser::parseNextCommand()), or by client
 * code.
 */

#include "ava6_public.h"

#ifndef AVA6__PARSER__COMMANDS_H
#define AVA6__PARSER__COMMANDS_H

#include <ava6/ava6.h>

#include <iosfwd>
#include <sstream>
#include <string>
#include <vector>

#include "options/language.h"

namespace ava6 {

class TermManager;
class Solver;
class Term;

namespace main {
class CommandExecutor;
}

namespace parser {

class CommandStatus;
class SymManager;

/**
 * Convert a symbolic expression to string. This method differs from
 * Term::toString in that it does not depend on the output language.
 *
 * @param sexpr the symbolic expression to convert
 * @return the symbolic expression as string
 */
std::string sexprToString(ava6::Term sexpr) AVA6_EXPORT;

/**
 * Encapsulation of a command.
 *
 * Commands are constructed by the input parser and can be invoked on
 * the solver and symbol manager.
 */
class AVA6_EXPORT Cmd
{
  friend class main::CommandExecutor;

 public:
  Cmd();
  Cmd(const Cmd& cmd);

  virtual ~Cmd();

  /**
   * Invoke the command on the solver and symbol manager sm.
   */
  virtual void invoke(ava6::Solver* solver, parser::SymManager* sm) = 0;
  /**
   * Same as above, and prints the result to output stream out.
   */
  virtual void invoke(ava6::Solver* solver,
                      parser::SymManager* sm,
                      std::ostream& out);
  /**
   * Same as invoke, but prints the result to the output stream associated to
   * the solver.
   */
  virtual void invokeAndPrintResult(ava6::Solver* solver,
                                    parser::SymManager* sm);

  /**
   * @return A string representation of this result.
   */
  std::string toString() const;

  /**
   * Get the name for this command, e.g. "assert".
   *
   * @return The name of this command.
   */
  virtual std::string getCommandName() const = 0;

  /**
   * Either the command hasn't run yet, or it completed successfully
   * (CommandSuccess, not CommandUnsupported or CommandFailure).
   *
   * @return Whether the command was successfully invoked.
   */
  bool ok() const;

  /**
   * The command completed in a failure state (CommandFailure, not
   * CommandSuccess or CommandUnsupported).
   *
   * @return Whether the command failed.
   */
  bool fail() const;

  /**
   * The command was ran but was interrupted due to resource limiting.
   *
   * @return Whether the command was interrupted.
   */
  bool interrupted() const;

 protected:
  virtual void toStream(std::ostream& out) const = 0;
  /**
   * This field contains a command status if the command has been
   * invoked, or NULL if it has not.  This field is either a
   * dynamically-allocated pointer, or it's a pointer to the singleton
   * CommandSuccess instance.  Doing so is somewhat asymmetric, but
   * it avoids the need to dynamically allocate memory in the common
   * case of a successful command.
   */
  const CommandStatus* d_commandStatus;
  /**
   * Print the result of running the command. This method is only called if the
   * command ran successfully.
   */
  virtual void printResult(ava6::Solver* solver, std::ostream& out) const;
  /**
   * Reset the given solver in-place (keep the object at the same memory
   * location).
   */
  static void resetSolver(ava6::Solver* solver);

  // These methods rely on Command being a friend of classes in the API.
  // Subclasses of command should use these methods for conversions,
  // which is currently necessary for e.g. printing commands.
  /** Helper to convert a Term to an internal internal::Node */
  static internal::Node termToNode(const ava6::Term& term);
  /** Helper to convert a vector of Terms to internal Nodes. */
  static std::vector<internal::Node> termVectorToNodes(
      const std::vector<ava6::Term>& terms);
  /** Helper to convert a Sort to an internal internal::TypeNode */
  static internal::TypeNode sortToTypeNode(const ava6::Sort& sort);
  /** Helper to convert a vector of Sorts to internal TypeNodes. */
  static std::vector<internal::TypeNode> sortVectorToTypeNodes(
      const std::vector<ava6::Sort>& sorts);
}; /* class Command */

/**
 * EmptyCommands are the residue of a command after the parser handles
 * them (and there's nothing left to do).
 */
class AVA6_EXPORT EmptyCommand : public Cmd
{
 public:
  EmptyCommand(std::string name = "");
  std::string getName() const;
  void invoke(ava6::Solver* solver, parser::SymManager* sm) override;
  std::string getCommandName() const override;
  void toStream(std::ostream& out) const override;

 protected:
  std::string d_name;
}; /* class EmptyCommand */

class AVA6_EXPORT EchoCommand : public Cmd
{
 public:
  EchoCommand(std::string output = "");

  std::string getOutput() const;

  void invoke(ava6::Solver* solver, parser::SymManager* sm) override;
  /** The result is the printed string */
  void printResult(ava6::Solver* solver, std::ostream& out) const override;

  std::string getCommandName() const override;
  void toStream(std::ostream& out) const override;

 protected:
  std::string d_output;
}; /* class EchoCommand */

class AVA6_EXPORT AssertCommand : public Cmd
{
 protected:
  ava6::Term d_term;

 public:
  AssertCommand(const ava6::Term& t);

  ava6::Term getTerm() const;

  void invoke(ava6::Solver* solver, parser::SymManager* sm) override;

  std::string getCommandName() const override;
  void toStream(std::ostream& out) const override;
}; /* class AssertCommand */

class AVA6_EXPORT PushCommand : public Cmd
{
 public:
  PushCommand(uint32_t nscopes);

  void invoke(ava6::Solver* solver, parser::SymManager* sm) override;
  std::string getCommandName() const override;
  void toStream(std::ostream& out) const override;

 private:
  uint32_t d_nscopes;
}; /* class PushCommand */

class AVA6_EXPORT PopCommand : public Cmd
{
 public:
  PopCommand(uint32_t nscopes);

  void invoke(ava6::Solver* solver, parser::SymManager* sm) override;
  std::string getCommandName() const override;
  void toStream(std::ostream& out) const override;

 private:
  uint32_t d_nscopes;
}; /* class PopCommand */

class AVA6_EXPORT DeclarationDefinitionCommand : public Cmd
{
 protected:
  std::string d_symbol;
  /**
   * Bind the symbol of this command to the given term. Return false if the
   * binding was invalid. In this case, set command status to CommandFailure.
   */
  bool bindToTerm(parser::SymManager* sm, ava6::Term t, bool doOverload);

 public:
  DeclarationDefinitionCommand(const std::string& id);

  void invoke(ava6::Solver* solver, parser::SymManager* sm) override = 0;
  std::string getSymbol() const;
}; /* class DeclarationDefinitionCommand */

class AVA6_EXPORT DeclareFunctionCommand : public DeclarationDefinitionCommand
{
 protected:
  std::vector<Sort> d_argSorts;
  ava6::Sort d_sort;

 public:
  DeclareFunctionCommand(const std::string& id,
                         const std::vector<Sort>& argSorts,
                         ava6::Sort sort);
  std::vector<Sort> getArgSorts() const;
  ava6::Sort getSort() const;

  void invoke(ava6::Solver* solver, parser::SymManager* sm) override;
  std::string getCommandName() const override;
  void toStream(std::ostream& out) const override;
}; /* class DeclareFunctionCommand */

class AVA6_EXPORT DeclarePoolCommand : public DeclarationDefinitionCommand
{
 protected:
  ava6::Sort d_sort;
  std::vector<ava6::Term> d_initValue;

 public:
  DeclarePoolCommand(const std::string& id,
                     ava6::Sort sort,
                     const std::vector<ava6::Term>& initValue);
  ava6::Sort getSort() const;
  const std::vector<ava6::Term>& getInitialValue() const;

  void invoke(ava6::Solver* solver, parser::SymManager* sm) override;
  std::string getCommandName() const override;
  void toStream(std::ostream& out) const override;
}; /* class DeclarePoolCommand */



class AVA6_EXPORT DeclareSortCommand : public DeclarationDefinitionCommand
{
 protected:
  size_t d_arity;

 public:
  DeclareSortCommand(const std::string& id, size_t arity);

  size_t getArity() const;

  void invoke(ava6::Solver* solver, parser::SymManager* sm) override;
  std::string getCommandName() const override;
  void toStream(std::ostream& out) const override;
}; /* class DeclareSortCommand */

class AVA6_EXPORT DefineSortCommand : public DeclarationDefinitionCommand
{
 protected:
  std::vector<ava6::Sort> d_params;
  ava6::Sort d_sort;

 public:
  DefineSortCommand(const std::string& id, ava6::Sort sort);
  DefineSortCommand(const std::string& id,
                    const std::vector<ava6::Sort>& params,
                    ava6::Sort sort);

  const std::vector<ava6::Sort>& getParameters() const;
  ava6::Sort getSort() const;

  void invoke(ava6::Solver* solver, parser::SymManager* sm) override;
  std::string getCommandName() const override;
  void toStream(std::ostream& out) const override;
}; /* class DefineSortCommand */

class AVA6_EXPORT DefineFunctionCommand : public DeclarationDefinitionCommand
{
 public:
  DefineFunctionCommand(const std::string& id,
                        ava6::Sort sort,
                        ava6::Term formula);
  DefineFunctionCommand(const std::string& id,
                        const std::vector<ava6::Term>& formals,
                        ava6::Sort sort,
                        ava6::Term formula);

  const std::vector<ava6::Term>& getFormals() const;
  ava6::Sort getSort() const;
  ava6::Term getFormula() const;

  void invoke(ava6::Solver* solver, parser::SymManager* sm) override;
  std::string getCommandName() const override;
  void toStream(std::ostream& out) const override;

 protected:
  /** The formal arguments for the function we are defining */
  std::vector<ava6::Term> d_formals;
  /** The co-domain sort of the function we are defining */
  ava6::Sort d_sort;
  /** The formula corresponding to the body of the function we are defining */
  ava6::Term d_formula;
}; /* class DefineFunctionCommand */

/**
 * The command when parsing define-fun-rec or define-funs-rec.
 * This command will assert a set of quantified formulas that specify
 * the (mutually recursive) function definitions provided to it.
 */
class AVA6_EXPORT DefineFunctionRecCommand : public Cmd
{
 public:
  DefineFunctionRecCommand(ava6::Term func,
                           const std::vector<ava6::Term>& formals,
                           ava6::Term formula);
  DefineFunctionRecCommand(const std::vector<ava6::Term>& funcs,
                           const std::vector<std::vector<ava6::Term>>& formals,
                           const std::vector<ava6::Term>& formula);

  const std::vector<ava6::Term>& getFunctions() const;
  const std::vector<std::vector<ava6::Term>>& getFormals() const;
  const std::vector<ava6::Term>& getFormulas() const;

  void invoke(ava6::Solver* solver, parser::SymManager* sm) override;
  std::string getCommandName() const override;
  void toStream(std::ostream& out) const override;

 protected:
  /** functions we are defining */
  std::vector<ava6::Term> d_funcs;
  /** formal arguments for each of the functions we are defining */
  std::vector<std::vector<ava6::Term>> d_formals;
  /** formulas corresponding to the bodies of the functions we are defining */
  std::vector<ava6::Term> d_formulas;
}; /* class DefineFunctionRecCommand */

/**
 * In separation logic inputs, which is an extension of smt2 inputs, this
 * corresponds to the command:
 *   (declare-heap (T U))
 * where T is the location sort and U is the data sort.
 */


/**
 * The command when parsing check-sat.
 * This command will check satisfiability of the input formula.
 */
class AVA6_EXPORT CheckSatCommand : public Cmd
{
 public:
  CheckSatCommand();
  ava6::Result getResult() const;
  void invoke(ava6::Solver* solver, parser::SymManager* sm) override;
  void printResult(ava6::Solver* solver, std::ostream& out) const override;
  std::string getCommandName() const override;
  void toStream(std::ostream& out) const override;

 private:
  ava6::Result d_result;
}; /* class CheckSatCommand */

/**
 * The command when parsing check-sat-assuming.
 * This command will assume a set of formulas and check satisfiability of the
 * input formula under these assumptions.
 */
class AVA6_EXPORT CheckSatAssumingCommand : public Cmd
{
 public:
  CheckSatAssumingCommand(ava6::Term term);
  CheckSatAssumingCommand(const std::vector<ava6::Term>& terms);

  const std::vector<ava6::Term>& getTerms() const;
  ava6::Result getResult() const;
  void invoke(ava6::Solver* solver, parser::SymManager* sm) override;
  void printResult(ava6::Solver* solver, std::ostream& out) const override;
  std::string getCommandName() const override;
  void toStream(std::ostream& out) const override;

 private:
  std::vector<ava6::Term> d_terms;
  ava6::Result d_result;
}; /* class CheckSatAssumingCommand */

// this is TRANSFORM in the CVC presentation language
class AVA6_EXPORT SimplifyCommand : public Cmd
{
 protected:
  ava6::Term d_term;
  ava6::Term d_result;

 public:
  SimplifyCommand(ava6::Term term);

  ava6::Term getTerm() const;
  ava6::Term getResult() const;
  void invoke(ava6::Solver* solver, parser::SymManager* sm) override;
  void printResult(ava6::Solver* solver, std::ostream& out) const override;
  std::string getCommandName() const override;
  void toStream(std::ostream& out) const override;
}; /* class SimplifyCommand */

class AVA6_EXPORT GetValueCommand : public Cmd
{
 protected:
  std::vector<ava6::Term> d_terms;
  std::vector<ava6::Term> d_result;

 public:
  GetValueCommand(ava6::Term term);
  GetValueCommand(const std::vector<ava6::Term>& terms);

  const std::vector<ava6::Term>& getTerms() const;
  const std::vector<ava6::Term>& getResult() const;
  void invoke(ava6::Solver* solver, parser::SymManager* sm) override;
  void printResult(ava6::Solver* solver, std::ostream& out) const override;
  std::string getCommandName() const override;
  void toStream(std::ostream& out) const override;
}; /* class GetValueCommand */

class AVA6_EXPORT GetModelDomainElementsCommand : public Cmd
{
 protected:
  ava6::Sort d_sort;
  std::vector<ava6::Term> d_result;

 public:
  GetModelDomainElementsCommand(ava6::Sort sort);
  ava6::Sort getSort() const;
  const std::vector<ava6::Term>& getResult() const;
  void invoke(ava6::Solver* solver, parser::SymManager* sm) override;
  void printResult(ava6::Solver* solver, std::ostream& out) const override;
  std::string getCommandName() const override;
  void toStream(std::ostream& out) const override;
}; /* class GetModelDomainElementsCommand */

class AVA6_EXPORT GetAssignmentCommand : public Cmd
{
 protected:
  ava6::Term d_result;

 public:
  GetAssignmentCommand();

  ava6::Term getResult() const;
  void invoke(ava6::Solver* solver, parser::SymManager* sm) override;
  void printResult(ava6::Solver* solver, std::ostream& out) const override;
  std::string getCommandName() const override;
  void toStream(std::ostream& out) const override;
}; /* class GetAssignmentCommand */

class AVA6_EXPORT GetModelCommand : public Cmd
{
 public:
  GetModelCommand();
  void invoke(ava6::Solver* solver, parser::SymManager* sm) override;
  void printResult(ava6::Solver* solver, std::ostream& out) const override;
  std::string getCommandName() const override;
  void toStream(std::ostream& out) const override;

 protected:
  /** Result of printing the model */
  std::string d_result;
}; /* class GetModelCommand */

/** The command to block models. */
class AVA6_EXPORT BlockModelCommand : public Cmd
{
 public:
  BlockModelCommand(modes::BlockModelsMode mode);

  void invoke(ava6::Solver* solver, parser::SymManager* sm) override;
  std::string getCommandName() const override;
  void toStream(std::ostream& out) const override;

 private:
  /** The mode to use for blocking. */
  modes::BlockModelsMode d_mode;
}; /* class BlockModelCommand */

/** The command to block model values. */
class AVA6_EXPORT BlockModelValuesCommand : public Cmd
{
 public:
  BlockModelValuesCommand(const std::vector<ava6::Term>& terms);

  const std::vector<ava6::Term>& getTerms() const;
  void invoke(ava6::Solver* solver, parser::SymManager* sm) override;
  std::string getCommandName() const override;
  void toStream(std::ostream& out) const override;

 protected:
  /** The terms we are blocking */
  std::vector<ava6::Term> d_terms;
}; /* class BlockModelValuesCommand */

class AVA6_EXPORT GetProofCommand : public Cmd
{
 public:
  GetProofCommand(modes::ProofComponent c = modes::ProofComponent::FULL);

  void invoke(ava6::Solver* solver, parser::SymManager* sm) override;

  void printResult(ava6::Solver* solver, std::ostream& out) const override;

  std::string getCommandName() const override;
  void toStream(std::ostream& out) const override;

 private:
  /** the result of the getProof call */
  std::string d_result;
  /** the requested proof component */
  modes::ProofComponent d_component;
}; /* class GetProofCommand */

class AVA6_EXPORT GetInstantiationsCommand : public Cmd
{
 public:
  GetInstantiationsCommand();

  static bool isEnabled(ava6::Solver* solver, const ava6::Result& res);
  void invoke(ava6::Solver* solver, parser::SymManager* sm) override;
  void printResult(ava6::Solver* solver, std::ostream& out) const override;
  std::string getCommandName() const override;
  void toStream(std::ostream& out) const override;

 protected:
  ava6::Solver* d_solver;
}; /* class GetInstantiationsCommand */

class AVA6_EXPORT GetUnsatAssumptionsCommand : public Cmd
{
 public:
  GetUnsatAssumptionsCommand();
  void invoke(ava6::Solver* solver, parser::SymManager* sm) override;
  std::vector<ava6::Term> getResult() const;
  void printResult(ava6::Solver* solver, std::ostream& out) const override;
  std::string getCommandName() const override;
  void toStream(std::ostream& out) const override;

 protected:
  std::vector<ava6::Term> d_result;
}; /* class GetUnsatAssumptionsCommand */

class AVA6_EXPORT GetUnsatCoreCommand : public Cmd
{
 public:
  GetUnsatCoreCommand();
  const std::vector<ava6::Term>& getUnsatCore() const;

  void invoke(ava6::Solver* solver, parser::SymManager* sm) override;
  void printResult(ava6::Solver* solver, std::ostream& out) const override;

  std::string getCommandName() const override;
  void toStream(std::ostream& out) const override;

 protected:
  /** The solver we were invoked with */
  ava6::Solver* d_solver;
  /** The symbol manager we were invoked with */
  parser::SymManager* d_sm;
  /** the result of the unsat core call */
  std::vector<ava6::Term> d_result;
}; /* class GetUnsatCoreCommand */

class AVA6_EXPORT GetUnsatCoreLemmasCommand : public Cmd
{
 public:
  GetUnsatCoreLemmasCommand();
  const std::vector<ava6::Term>& getUnsatCoreLemmas() const;

  void invoke(ava6::Solver* solver, parser::SymManager* sm) override;
  void printResult(ava6::Solver* solver, std::ostream& out) const override;

  std::string getCommandName() const override;
  void toStream(std::ostream& out) const override;

 protected:
  /** The solver we were invoked with */
  ava6::Solver* d_solver;
  /** the result of the unsat core call */
  std::vector<ava6::Term> d_result;
}; /* class GetUnsatCoreLemmasCommand */

class AVA6_EXPORT GetDifficultyCommand : public Cmd
{
 public:
  GetDifficultyCommand();
  const std::map<ava6::Term, ava6::Term>& getDifficultyMap() const;

  void invoke(ava6::Solver* solver, parser::SymManager* sm) override;
  void printResult(ava6::Solver* solver, std::ostream& out) const override;

  std::string getCommandName() const override;
  void toStream(std::ostream& out) const override;

 protected:
  /** The symbol manager we were invoked with */
  parser::SymManager* d_sm;
  /** the result of the get difficulty call */
  std::map<ava6::Term, ava6::Term> d_result;
};

class AVA6_EXPORT GetTimeoutCoreCommand : public Cmd
{
 public:
  GetTimeoutCoreCommand(const std::vector<Term>& assumptions);
  GetTimeoutCoreCommand();
  ava6::Result getResult() const;
  const std::vector<ava6::Term>& getTimeoutCore() const;

  void invoke(ava6::Solver* solver, parser::SymManager* sm) override;
  void printResult(ava6::Solver* solver, std::ostream& out) const override;

  std::string getCommandName() const override;
  void toStream(std::ostream& out) const override;

 protected:
  /** The solver we were invoked with */
  ava6::Solver* d_solver;
  /** The symbol manager we were invoked with */
  parser::SymManager* d_sm;
  /** Assumptions */
  std::vector<Term> d_assumptions;
  /** the result of the timeout core call */
  std::pair<ava6::Result, std::vector<ava6::Term>> d_result;
};

class AVA6_EXPORT GetLearnedLiteralsCommand : public Cmd
{
 public:
  GetLearnedLiteralsCommand(modes::LearnedLitType t);
  const std::vector<ava6::Term>& getLearnedLiterals() const;

  void invoke(ava6::Solver* solver, parser::SymManager* sm) override;
  void printResult(ava6::Solver* solver, std::ostream& out) const override;

  std::string getCommandName() const override;
  void toStream(std::ostream& out) const override;

 protected:
  /** the result of the get learned literals call */
  std::vector<ava6::Term> d_result;
  /** The type of learned literals to get */
  modes::LearnedLitType d_type;
};

class AVA6_EXPORT GetAssertionsCommand : public Cmd
{
 protected:
  std::string d_result;

 public:
  GetAssertionsCommand();

  void invoke(ava6::Solver* solver, parser::SymManager* sm) override;
  std::string getResult() const;
  void printResult(ava6::Solver* solver, std::ostream& out) const override;
  std::string getCommandName() const override;
  void toStream(std::ostream& out) const override;
}; /* class GetAssertionsCommand */

class AVA6_EXPORT SetBenchmarkLogicCommand : public Cmd
{
 protected:
  std::string d_logic;

 public:
  SetBenchmarkLogicCommand(std::string logic);

  std::string getLogic() const;
  void invoke(ava6::Solver* solver, parser::SymManager* sm) override;
  std::string getCommandName() const override;
  void toStream(std::ostream& out) const override;
}; /* class SetBenchmarkLogicCommand */

class AVA6_EXPORT SetInfoCommand : public Cmd
{
 protected:
  std::string d_flag;
  std::string d_value;

 public:
  SetInfoCommand(const std::string& flag, const std::string& value);

  const std::string& getFlag() const;
  const std::string& getValue() const;

  void invoke(ava6::Solver* solver, parser::SymManager* sm) override;
  std::string getCommandName() const override;
  void toStream(std::ostream& out) const override;
}; /* class SetInfoCommand */

class AVA6_EXPORT GetInfoCommand : public Cmd
{
 protected:
  std::string d_flag;
  std::string d_result;

 public:
  GetInfoCommand(std::string flag);

  std::string getFlag() const;
  std::string getResult() const;

  void invoke(ava6::Solver* solver, parser::SymManager* sm) override;
  void printResult(ava6::Solver* solver, std::ostream& out) const override;
  std::string getCommandName() const override;
  void toStream(std::ostream& out) const override;
}; /* class GetInfoCommand */

class AVA6_EXPORT SetOptionCommand : public Cmd
{
 protected:
  std::string d_flag;
  std::string d_value;

 public:
  SetOptionCommand(const std::string& flag, const std::string& value);

  const std::string& getFlag() const;
  const std::string& getValue() const;

  void invoke(ava6::Solver* solver, parser::SymManager* sm) override;
  std::string getCommandName() const override;
  void toStream(std::ostream& out) const override;
}; /* class SetOptionCommand */

class AVA6_EXPORT GetOptionCommand : public Cmd
{
 protected:
  std::string d_flag;
  std::string d_result;

 public:
  GetOptionCommand(std::string flag);

  std::string getFlag() const;
  std::string getResult() const;

  void invoke(ava6::Solver* solver, parser::SymManager* sm) override;
  void printResult(ava6::Solver* solver, std::ostream& out) const override;
  std::string getCommandName() const override;
  void toStream(std::ostream& out) const override;
}; /* class GetOptionCommand */

class AVA6_EXPORT DatatypeDeclarationCommand : public Cmd
{
 private:
  std::vector<ava6::Sort> d_datatypes;

 public:
  DatatypeDeclarationCommand(const ava6::Sort& datatype);

  DatatypeDeclarationCommand(const std::vector<ava6::Sort>& datatypes);
  const std::vector<ava6::Sort>& getDatatypes() const;
  void invoke(ava6::Solver* solver, parser::SymManager* sm) override;
  std::string getCommandName() const override;
  void toStream(std::ostream& out) const override;
}; /* class DatatypeDeclarationCommand */

class AVA6_EXPORT ResetCommand : public Cmd
{
 public:
  ResetCommand() {}
  void invoke(ava6::Solver* solver, parser::SymManager* sm) override;
  std::string getCommandName() const override;
  void toStream(std::ostream& out) const override;
}; /* class ResetCommand */

class AVA6_EXPORT ResetAssertionsCommand : public Cmd
{
 public:
  ResetAssertionsCommand() {}
  void invoke(ava6::Solver* solver, parser::SymManager* sm) override;
  std::string getCommandName() const override;
  void toStream(std::ostream& out) const override;
}; /* class ResetAssertionsCommand */

class AVA6_EXPORT QuitCommand : public Cmd
{
 public:
  QuitCommand() {}
  void invoke(ava6::Solver* solver, parser::SymManager* sm) override;
  std::string getCommandName() const override;
  void toStream(std::ostream& out) const override;
}; /* class QuitCommand */

}  // namespace parser
}  // namespace ava6

#endif /* AVA6__PARSER__COMMAND_H */
