/******************************************************************************
 * This file is part of the cvc5 project.
 *
 * Copyright (c) 2009-2026 by the authors listed in the file AUTHORS
 * in the top-level source directory and their institutional affiliations.
 * All rights reserved.  See the file COPYING in the top-level source
 * directory for licensing information.
 * ****************************************************************************
 *
 * Model object for the non-linear extension class.
 */

#ifndef AVA6__THEORY__ARITH__NL__NL_MODEL_H
#define AVA6__THEORY__ARITH__NL__NL_MODEL_H

#include <map>
#include <unordered_map>
#include <vector>

#include "expr/kind.h"
#include "expr/node.h"
#include "smt/env_obj.h"
#include "theory/arith/arith_subs.h"

namespace ava6::context {
class Context;
}

namespace ava6::internal {

namespace theory {

class TheoryModel;

namespace arith {
namespace nl {

class NonlinearExtension;

/** Non-linear model finder
 *
 * This class is responsible for all queries related to the (candidate) model
 * that is being processed by the non-linear arithmetic solver. It further
 * implements techniques for finding modifications to the current candidate
 * model in the case it can determine that a model exists. These include
 * techniques based on solving equalities by exact substitution.
 */
class NlModel : protected EnvObj
{
  friend class NonlinearExtension;

 public:
  NlModel(Env& env);
  ~NlModel();
  /**
   * This method is called once at the beginning of a last call effort check,
   * where m is the model of the theory of arithmetic. This method resets the
   * cache of computed model values.
   */
  void reset(const std::map<Node, Node>& arithModel);
  /**
   * This method is called when the non-linear arithmetic solver restarts
   * its computation of lemmas and models during a last call effort check.
   */
  void resetCheck();
  /**
   * This computes model values for terms based on two semantics, a "concrete"
   * semantics and an "abstract" semantics.
   *
   * if isConcrete is true, this means compute the value of n based on its
   *          children recursively. (we call this its "concrete" value)
   * if isConcrete is false, this means lookup the value of n in the model.
   *          (we call this its "abstract" value)
   * In other words, !isConcrete treats multiplication terms as variables,
   * whereas isConcrete computes their
   * actual values based on the semantics of multiplication. This is a key
   * distinction used in the model-based refinement scheme in Cimatti et al.
   * TACAS 2017.
   *
   * For example, if M( a ) = 2, M( b ) = 3, M( a*b ) = 5, i.e. the variable
   * for a*b has been assigned a value 5 by the linear solver, then :
   *
   *   computeModelValue( a*b, true ) =
   *   computeModelValue( a, true )*computeModelValue( b, true ) = 2*3 = 6
   * whereas:
   *   computeModelValue( a*b, false ) = 5
   */
  Node computeConcreteModelValue(TNode n);
  Node computeAbstractModelValue(TNode n);
  Node computeModelValue(TNode n, bool isConcrete);

  /**
   * Compare arithmetic terms i and j based an ordering.
   *
   * This returns:
   *  -1 if i < j, 1 if i > j, or 0 if i == j
   *
   * If isConcrete is true, we consider the concrete model values of i and j,
   * otherwise, we consider their abstract model values. For definitions of
   * concrete vs abstract model values, see NlModel::computeModelValue.
   *
   * If isAbsolute is true, we compare the absolute value of the above
   * values.
   */
  int compare(TNode i, TNode j, bool isConcrete, bool isAbsolute);
  /**
   * Compare arithmetic terms i and j based an ordering.
   *
   * This returns:
   *  -1 if i < j, 1 if i > j, or 0 if i == j
   *
   * If isAbsolute is true, we compare the absolute value of i and j
   */
  int compareValue(TNode i, TNode j, bool isAbsolute) const;

  //------------------------------ recording model substitutions
  /**
   * Adds the model substitution v -> s. This applies the substitution
   * { v -> s } to each term in d_substitutions and then adds v,s to
   * d_substitutions.
   * If this method returns false, then the substitution v -> s is inconsistent
   * with the current substitution.
   */
  bool addSubstitution(TNode v, TNode s);
  /** Check that all assertions hold under the exact model substitutions. */
  bool checkModel(const std::vector<Node>& assertions);
  //------------------------------ end recording model substitutions

  /**
   * This prints both the abstract and concrete model values for arithmetic
   * term n on Trace c with precision prec.
   */
  void printModelValue(const char* c, Node n, unsigned prec = 5) const;
  /**
   * This gets mappings that indicate how to repair the model generated by the
   * linear arithmetic solver. This method should be called after a successful
   * call to checkModel above.
   *
   * The mapping arithModel is updated by this method to map arithmetic terms v
   * to their (exact) value that was computed during checkModel.
   */
  void getModelValueRepair(std::map<Node, Node>& arithModel);

  /** Return the substituted form of s */
  Node getSubstitutedForm(TNode s) const;

 private:
  /** Cache for concrete model values */
  std::map<Node, Node> d_concreteModelCache;
  /** Cache for abstract model values */
  std::map<Node, Node> d_abstractModelCache;

  /**
   * The values that the arithmetic theory solver assigned in the model. This
   * corresponds to the set of equalities that linear solver (via TheoryArith)
   * is currently sending to TheoryModel during collectModelValues, plus
   * additional entries x -> 0 for variables that were unassigned by the linear
   * solver.
   */
  std::map<Node, Node> d_arithVal;

  /**
   * A substitution from variables that appear in assertions to a solved form
   * term.
   */
  ArithSubs d_substitutions;

  /** Get the model value of n from the model object above */
  Node getValueInternal(TNode n);

  /** Does v have a substitution in the current model check? */
  bool hasAssignment(Node v) const;

  /**
   * Checks whether we have a linear model value for v, i.e. whether v is
   * contained in d_arithVal. If so, we also store the value that v is mapped
   * to in val.
   */
  bool hasLinearModelValue(TNode v, Node& val) const;

  //---------------------------check model
  /** Solve an equality by an exact substitution and record it if successful. */
  bool solveEqualitySimple(Node eq);
  //---------------------------end check model

  /** Commonly used constants. */
  Node d_zero;
  Node d_one;
  /** Equalities satisfied by construction, mapped to the solved variable. */
  std::unordered_map<Node, Node> d_check_model_solved;
}; /* class NlModel */

}  // namespace nl
}  // namespace arith
}  // namespace theory
}  // namespace ava6::internal

#endif /* AVA6__THEORY__ARITH__NONLINEAR_EXTENSION_H */
