# kinds.toml
#
# For documentation on this file format, please refer to
# src/theory/builtin/kinds.toml.
#

[theory]
id                 = "THEORY_SETS"
base_class         = "::ava6::internal::theory::sets::TheorySets"
base_class_header  = "theory/sets/theory_sets.h"
properties         = ["parametric", "check", "presolve"]
typechecker_header = "theory/sets/theory_sets_type_rules.h"

[rewriter]
class  = "::ava6::internal::theory::sets::TheorySetsRewriter"
header = "theory/sets/theory_sets_rewriter.h"

# constants
[[kinds]]
type      = "constant"
name      = "SET_EMPTY"
class_key = "class"
cpp_type  = "EmptySet"
hasher    = "::ava6::internal::EmptySetHashFunction"
header    = "expr/emptyset.h"
comment   = "the empty set constant; payload is an instance of the ava6::internal::EmptySet class"
typerule  = "::ava6::internal::theory::sets::EmptySetTypeRule"

# the type
[[kinds]]
type     = "operator"
name     = "SET_TYPE"
children = 1
comment  = "set type, takes as parameter the type of the elements"
[kinds.cardinality]
computer = "::ava6::internal::theory::sets::SetsProperties::computeCardinality(%TYPE%)"
header   = "theory/sets/theory_sets_type_rules.h"
[kinds.well-founded]
wellfoundedness-computer = "::ava6::internal::theory::sets::SetsProperties::isWellFounded(%TYPE%)"
ground-term-computer     = "::ava6::internal::theory::sets::SetsProperties::mkGroundTerm(%TYPE%)"
header                   = "theory/sets/theory_sets_type_rules.h"
[kinds.enumerator]
class  = "::ava6::internal::theory::sets::SetEnumerator"
header = "theory/sets/theory_sets_type_enumerator.h"

# operators
[[kinds]]
type      = "operator"
name      = "SET_UNION"
children  = 2
comment   = "set union"
typerule  = "::ava6::internal::theory::sets::SetsBinaryOperatorTypeRule"
construle = "::ava6::internal::theory::sets::SetsBinaryOperatorTypeRule"

[[kinds]]
type     = "operator"
name     = "SET_INTER"
children = 2
comment  = "set intersection"
typerule = "::ava6::internal::theory::sets::SetsBinaryOperatorTypeRule"

[[kinds]]
type     = "operator"
name     = "SET_MINUS"
children = 2
comment  = "set subtraction"
typerule = "::ava6::internal::theory::sets::SetsBinaryOperatorTypeRule"

[[kinds]]
type     = "operator"
name     = "SET_SUBSET"
children = 2
comment  = "subset predicate; first parameter a subset of second"
typerule = "::ava6::internal::theory::sets::SubsetTypeRule"

[[kinds]]
type     = "operator"
name     = "SET_MEMBER"
children = 2
comment  = "set membership predicate; first parameter a member of second"
typerule = "::ava6::internal::theory::sets::MemberTypeRule"

[[kinds]]
type      = "operator"
name      = "SET_SINGLETON"
children  = 1
comment   = "constructs a set of a single element. First parameter is a term"
typerule  = "::ava6::internal::theory::sets::SingletonTypeRule"
construle = "::ava6::internal::theory::sets::SingletonTypeRule"

[[kinds]]
type     = "operator"
name     = "SET_INSERT"
children = "2:"
comment  = "set obtained by inserting elements (first N-1 parameters) into a set (the last parameter)"
typerule = "::ava6::internal::theory::sets::InsertTypeRule"

[[kinds]]
type     = "operator"
name     = "SET_COMPREHENSION"
children = 3
comment  = "set comprehension specified by a bound variable list, a predicate, and a term."
typerule = "::ava6::internal::theory::sets::ComprehensionTypeRule"

# The operator choose returns an element from a given set.
# If set A = {x}, then the term (choose A) is equivalent to the term x.
# If the set is empty, then (choose A) is an arbitrary value.
# If the set has cardinality > 1, then (choose A) will deterministically return an element in A.
[[kinds]]
type     = "operator"
name     = "SET_CHOOSE"
children = 1
comment  = "return an element in the set given as a parameter"
typerule = "::ava6::internal::theory::sets::ChooseTypeRule"

# The operator set.is_empty returns whether the given set is empty
[[kinds]]
type     = "operator"
name     = "SET_IS_EMPTY"
children = 1
comment  = "return whether the given set is empty"
typerule = "::ava6::internal::theory::sets::IsSetTypeRule"

# The operator is_singleton returns whether the given set is a singleton
[[kinds]]
type     = "operator"
name     = "SET_IS_SINGLETON"
children = 1
comment  = "return whether the given set is a singleton"
typerule = "::ava6::internal::theory::sets::IsSetTypeRule"

# The set.map operator applies the first argument, a function of type (-> T1 T2), to every element
# of the second argument, a set of type (Set T1), and returns a set of type (Set T2).
[[kinds]]
type     = "operator"
name     = "SET_MAP"
children = 2
comment  = "set map function"
typerule = "::ava6::internal::theory::sets::SetMapTypeRule"

# The set.filter operator takes a predicate of type (-> T Bool) and a set of type (Set T)
# and returns the same set excluding those elements that do not satisfy the predicate
[[kinds]]
type     = "operator"
name     = "SET_FILTER"
children = 2
comment  = "set filter operator"
typerule = "::ava6::internal::theory::sets::SetFilterTypeRule"

# set.all operator is a predicate that holds iff all elements in a given set satisfy the the given predicate.
# (set.all p A) receives a predicate p of type (-> T Bool) and a set of type (Set T) and returns Bool
[[kinds]]
type     = "operator"
name     = "SET_ALL"
children = 2
comment  = "set all operator"
typerule = "::ava6::internal::theory::sets::SetAllSomeTypeRule"

# set.some operator is a predicate that holds iff at least one element in a given set satisfies the the given predicate.
# (set.some p A) receives a predicate p of type (-> T Bool) and a set of type (Set T) and returns Bool
[[kinds]]
type     = "operator"
name     = "SET_SOME"
children = 2
comment  = "set some operator"
typerule = "::ava6::internal::theory::sets::SetAllSomeTypeRule"

# set.fold operator combines elements of a set into a single value.
# (set.fold f t A) folds the elements of set A starting with term t and using
# the combining function f.
#  f: a binary operation of type (-> T1 T2 T2)
#  t: an initial value of type T2
#  A: a bag of type (Set T1)
[[kinds]]
type     = "operator"
name     = "SET_FOLD"
children = 3
comment  = "set fold operator"
typerule = "::ava6::internal::theory::sets::SetFoldTypeRule"

# rel.group operator
[[kinds]]
type = "operator"
name     = "SET_EMPTY_OF_TYPE"
children = 1
comment  = "the empty set whose argument represents its type"
typerule = "::ava6::internal::theory::sets::SetEmptyOfTypeTypeRule"
